spring.application.name=logiroute

# DATASOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/logiroute_db?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# SQL INIT (desactivado - ejecutar schema-completo.sql manualmente)
spring.sql.init.mode=never

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# LOGGING
logging.level.com.logiroute=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# SERVER
server.port=8080
server.error.include-message=always

# GUAVA + CACHE
logiroute.cache.expire-minutes=10
logiroute.rate-limiter.per-second=10

# JWT
jwt.secret=logiroute-secret-key-that-should-be-changed-in-production-environment-2024
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:8080